# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a1c96c57da46c9e1dbdf3827677d0c7be2690ffb61adc6034d95d5dca74b1ffd709884ccf4f4f24ead492118fb4284251c4d2ace90079121c4e4884e61a731b

test:
  secret_key_base: 7320239a683f123025d2e7eb9c0906218208c8470ea32a94bd4a8c18b7168c552166df9145c78dba1c10f672386ec3451ddf4c2ef4640310d3cdb8de666d1dcb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
